### ISSUE TITLE
Safari Mac Pressure sometimes not working

### ISSUE THREAD

**Issue by evgenyrodionov** [stuyam/pressure#5]
![image](https://cloud.githubusercontent.com/assets/775692/12531078/81091022-c203-11e5-94b4-6bc5a7df076a.png)

**Comment by yamartino** [comment]
@theaqua thanks for bringing this to my attention. So you are testing on your trackpad on your laptop that has force touch? I have an external trackpad and sometimes I forget and use what which doesn't work obviously, but I just want to make sure. When you refresh safari and try again does it fail every time? Do any of the examples work?

**Comment by theaqua** [comment]
@yamartino yep, it's trackpad on a laptop, I don't have external one or mouse. It fails every time, examples don't work :(

**Comment by yamartino** [comment]
@theaqua try restarting Safari, there is a bug in Safari that I have tried to alert Apple about. If Safari is open for too long sometimes their pressure events stop working. Thanks for helping me out! Let me know if that works :)

**Comment by theaqua** [comment]
You're right! Thanks, you give me an answer why Quick Look suddenly stops working.

**Comment by dcorb** [comment]
Same here
![image](https://cloud.githubusercontent.com/assets/881333/13433172/99dc9870-dfc8-11e5-8d24-31ca5478d2ba.png)
Force quitting Safari didn't work

**Comment by dcorb** [comment]
@yamartino still the same after rebooting. It says not supported. Safari 9.0.3
Tell me if I can do something to help you. I tried by my own in this codepen .. no luck neither. 
http://codepen.io/dcorb/pen/WwvXOv

**Comment by yamartino** [comment]
@dcorb thanks for the feedback and the testing you have done to help. I made a small jsfiddle: https://jsfiddle.net/2eLdv0qc/5/ Give it a test, when you are in safari and click the red box, does it give you an alert and console log? This example is basically directly off of Apple's documentation, I am just curious to see that it works at all before debugging pressure. Thanks for all of the help, this is great!

**Comment by dcorb** [comment]
Your test case in jsfiddle doesn't work for me. So there is little that pressurejs can do here I guess. I rebooted, still same.

**Comment by yamartino** [comment]
@dcorb sorry to hear that. Yeah sounds like there may be a bug in safari for you. Not sure what is happening there. Bummer that safari is so buggy. I hope it gets better for pressure's and your sake. Thank you for all the help trying to work through this. Closing for now until someone else finds another safari bug ;)

**Comment by yamartino** [comment]
Anyone having issues with Safari on a 2015 of higher Macbook Pro, reference this thread!

**Comment by jespertheend** [comment]
I was having issues with force touch on the trackpad not working. Turned out I had the 'Force Click and haptic feedback' disabled in system preferences.
<img width="334" alt="screen shot 2017-07-30 at 17 40 12" src="https://user-images.githubusercontent.com/2737650/28755247-3967efcc-754e-11e7-952e-b1fba34491d8.png">
