### ISSUE TITLE
Jquery pressure

### ISSUE THREAD

**Issue by lales12** [stuyam/pressure#53]
I think  jquery.pressure.js has a misspell on the last line, this method return Jquery.pressure I think must be jQuery.pressure.

______________
**Please provide information about the device you are seeing the issue on**
I found this error on the last release. you can see the error on the console when try to include this file

**Comment by zetlen** [comment]
Whoops! This is absolutely due to my PR, sorry @lales12. I forgot to add an exports configuration. Stand by please.

**Comment by stuyam** [comment]
Thanks for the help @zetlen, this was fixed in the newest version v2.0.3
