### ISSUE TITLE
Where is the supportLegacyTest function?

### ISSUE THREAD

**Issue by davidshimjs** [stuyam/pressure#64]
I have found an error "this.supportLegacyTest is not a function.".
I can't find definition of supportLegacyTest.

**Comment by davidshimjs** [comment]
I have fixed this issue on https://github.com/stuyam/pressure/pull/63

**Comment by stuyam** [comment]
Thanks for this ⚡️

**Comment by stuyam** [comment]
Fixed in v2.1.1
