### ISSUE TITLE
50-100% being thought as 0-50%

### ISSUE THREAD

**Issue by Nythepegasus** [stuyam/pressure#69]
I assume this is not very important, but I still want to say something just in case. Sometimes when you push the touchpad all the way down, and then lightly release, it'll start thinking pushing all the way down is only 50% This happens very rarely.. 
______________
**Please provide information about the device you are seeing the issue on**
Device is a Early 2015 Macbook Pro
Operating system is macOS Sierra 10.12.6
Browser is Safari 10.1.2

**Comment by stuyam** [comment]
That is very strange. It almost sounds like it may be an Apple bug but not sure. They have had some weird bugs with the trackpad and safari but I will try to reproduce and see what I can find out! 😄

**Comment by stuyam** [comment]
Closing unless there is more evidence of this and can be reproduced.
