### ISSUE TITLE
Android devices Polyfill not working

### ISSUE THREAD

**Issue by rubcuadra** [stuyam/pressure#71]
On some Android devices it goes from 0 to 1 just by touching it, fixed it on my project by adding the only with "touch" if I found out that the user is using a mobile device, I believe that the android phone is crashing with the pointer event, if you try the widgets on the pressure.js page you will find that "Targets All" and "Targets ONLY POINTER events" have this weird effect from 0 to 1 but on the "ONLY Force touch" it does work. tested it on a Moto G4 play and a shitty Chinese Android phone(I use it a lot for testing, if something runs on it then it will run anywhere)

______________
**Please provide information about the device you are seeing the issue on**
Device is a Moto g4 play
Operating system is Android 5.0 and 6.0 
Browser is Chrome

**Comment by stuyam** [comment]
Duplicate: #67

**Comment by stuyam** [comment]
Closing and refer to #67
