### ISSUE TITLE
How to detect if pressure.js is already binded to an element?

### ISSUE THREAD

**Issue by MickL** [stuyam/pressure#73]
I want to prevent binding pressure.js to an element that already has pressure.js. How may i detect that?

Something like:

```
if(!$(someElement).pressure) {
   $(someElement).pressure();
}
```

**Comment by stuyam** [comment]
Hi @MickL,
There currently isn't a way I can think of to test if an element is bound to pressure. It seems like it would make sense to do so.

For now you could so something like add a property on any element that has been bound to pressure that you can check later. For example:
```javascript
$(someElement).pressure();
$(someElement).data('pressure-bound', true);
...
...
if( !$('someElement').data('pressure-bound') ){
  // do something
}
```

But I will look into how we could provide this as a feature. If anyone has any ideas I'm all ears.

**Comment by MickL** [comment]
Yes thanks i did it by adding a class. Feature would be nice but it is not a major issue.
