### ISSUE TITLE
Not going to 1 when 3D Touch is set to “Firm”

### ISSUE THREAD

**Issue by MarkSmit** [stuyam/pressure#76]
When you set 3D Touch to “Firm” in settings > general > accessibility > 3D Touch it won’t go to 1 it stucks on 0.833333...

______________
Device is a 2017 iPhone X
Operating system is iOS 11.4.1
Browser is Safari on iOS 11.4.1

**Comment by stuyam** [comment]
Does it continue if you restart your phone? When you change the settings from Firm to Regular to Light does it make a difference? I have tried a number of those things and have not been able to reproduce what you are experiencing.

**Comment by MarkSmit** [comment]
On Light and Regular it is functioning properly. Maybe it is a bug, I will report it to Apple.

**Comment by stuyam** [comment]
Cool thanks 👍
