### ISSUE TITLE
Force Touch not working properly Safari 13

### ISSUE THREAD

**Issue by zanderp25** [stuyam/pressure#81]
When I use force touch, it reverts to polyfill. When I go to the 'Pressure Change' section on the website, the "Targets All" bar uses polyfill, but the 'Force Touch' bar works as it should.

Edit: It still does not work, probably has something to do with the new Safari 13 update

Edit 2: Still does not work in Safari 14
______________
Device: 2017 Apple MacBook Pro
OS: macOS Mojave 10.14.6 - macOS Catalina 10.15.2
Browser: Safari 13.0.1 - Safari 14.0

**Comment by MickL** [comment]
Same here on macOS Catalina. I tested Chrome, Safari and Firefox all show "Your device does not support force touch or 3d touch so Pressure.js has fallen back to the polyfill.".


**Safari**
Targets All -> Not working
Targets ONLY Force Touch (mouse) -> Working

**Chrome**
Targets All -> Not working
Targets ONLY Force Touch (mouse) -> Not working

**Firefox**
Targets All -> Not working
Targets ONLY Force Touch (mouse) -> Not working

**Comment by zehle** [comment]
I'm just here to say that I get the same result. I'm on a Macbook Pro. "_Targets All_" falls back to polyfill while "_Targets ONLY Force Touch (mouse)_" works as expected. Safari 13.1.2

**Comment by theLMGN** [comment]
Still having this issue. Pressure still works on iOS though.

**Comment by zanderp25** [comment]
Update: I have updated to Safari 14.0 for macOS and it still doesn't work

**Comment by stuyam** [comment]
Released in: https://github.com/stuyam/pressure/releases/tag/v2.2.0
