### ISSUE TITLE
Safari on macOS not responding to pressure input

### ISSUE THREAD

**Issue by oseph** [stuyam/pressure#85]
Firstly, thanks for pressure.js! This is a great and super handy library.

I'm working on a very basic drawing app which successfully detects pressure input in Firefox and Safari on iOS when using Apple Pencil, but it does not respond to pressure input when using Safari on macOS.

From what I can tell from the examples on the main Pressurejs.com page, pressure input is defaulting to polyfill when I use Safari as well ...

(My drawing "app" can be found at holinaty.com/draw if you're curious) 
______________
Info about my setup:
Device is a: 2019 macbook pro 16"
Operating system: macOS Catalina 10.15.5
Browser: Safari 13.1.1

**Comment by stuyam** [comment]
Duplicate: #81

**Comment by stuyam** [comment]
Released: https://github.com/stuyam/pressure/releases/tag/v2.2.0
